name: Release

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  FORCE_COLOR: true

jobs:
  test:
    uses: ./.github/workflows/test.yml

  changelog:
    name: Changelog PR or Release
    # if: ${{ github.repository_owner == 'openInula' }}
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Packages
        run: pnpm run build

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm exec changeset version
          publish: pnpm exec changeset publish
          commit: "chore(release): release in ci"
          title: "chore(release): release in ci"
        env:
          # Needs access to push to main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Needs access to publish to npm
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}